### ISSUE TITLE
Does not run, exec: : not found

### ISSUE THREAD

**Issue by probonopd** [harshjv/donut#1]
On Ubuntu 16.04:

```
$ '/home/me/Downloads/donut-1.2.0-x86_64.AppImage' 
/tmp/.mount_DGUSID
3102
/tmp/.mount_DGUSID/AppRun: line 43: exec: : not found
```

**Comment by harshjv** [comment]
Have you tried this?

```
chmod a+x donut-1.2.0-x86_64.AppImage
./donut-1.2.0-x86_64.AppImage
```

**Comment by probonopd** [comment]
Yes

**Comment by harshjv** [comment]
@probonopd I didn't notice that `AppImageKit` is your creation. 😅

Can you throw some light on what could be the problem?

I am using https://github.com/electron-userland/electron-builder to build AppImage files.

**Comment by probonopd** [comment]
Done, it indeed appears to be an upstream issue with electron-builder. Opened a ticket there:
https://github.com/electron-userland/electron-builder/issues/827

**Comment by harshjv** [comment]
Thanks @probonopd :)
