### ISSUE TITLE
The .exe doesn't work  

### ISSUE THREAD

**Issue by luis-herasme** [harshjv/donut#2]
When i click in the .exe appears a window for a few second and then is closed, but i can see the icon in the control panel.

**Comment by harshjv** [comment]
Can you share the screenshot of the screen after you click the control panel icon?
Clicking the icon should open Donut's interface.

**Comment by luis-herasme** [comment]
I uninstall it and reinstall it and it worked, but now i can't find the .exe or some shortcut to open the program.

**Comment by harshjv** [comment]
@LuisHerasme Is this still happening?
